---
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index for CentOS
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"
  - name: install updates for Ubuntu
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - Elastic
    - Kibana
    - logstash
