- name: elastic search package for ubuntu
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  when: ansible_distribution == "Ubuntu"

- name: ubuntu update
  apt:  
    upgrade: dist
    update_cache: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: install elastic search in ubuntu
  apt:
    name: elasticsearch
    state: present
  when: ansible_distribution == "Ubuntu"

- name: download elasticsearch in CentOS
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.2-x86_64.rpm
    dest: /tmp/elasticsearch-7.9.2-x86_64.rpm
  when: ansible_distribution == "CentOS"

- name: install elesticsearch for CentOS
  yum:
    name: /tmp/elasticsearch-7.9.2-x86_64.rpm
    state: present
  when: ansible_distribution == "CentOS"

- name: Start Elastic search
  service:
    name: elasticsearch
    state: started


